### ISSUE TITLE
2D Tricube distribution problem

### ISSUE THREAD

**Issue by aiboys** [qjadud1994/TricubeNet#1]
Hi,
   Thanks for your open source. It is a good work. But I have the following problems:
1）2d tricube distribution is defined as (1-|x|^3)^r * (1-|y|^3)^r, such distribution is invariant with object's shape (aspect-ratio between height and width).  But shown in Fig 7, the output heatmaps are deformable with the shape、aspect ratio and rotation degree. So I amd not sure that there is a modification in your 2d tricube distribution, right?
![image](https://user-images.githubusercontent.com/45069071/160407910-df1a9a8b-f233-4c2b-a98c-dc451ce1ec2a.png)
![image](https://user-images.githubusercontent.com/45069071/160408396-5caa50dd-c4e0-4ca2-a25f-09584953bded.png)

2) since segmentation based algorithms need post-processing, how about the time-consumption of your TricubeNet. I did not see the comparison experiments with other SOTA algorithms.

**Comment by qjadud1994** [comment]
Thank you for your interest in our work.

1. Actually, we pre-define the square 2D Tricube kernel as in Figure 3 (a) and reshape the kernel according to the shape of an object as in Figure 3 (c).
You can notice this implementation in [here](https://github.com/qjadud1994/TricubeNet/blob/8c42c5c97d52e716b2567eead50d595839e1f129/loader.py#L47-L48).

2. In our pre-print version, our work measured the latency using another backbone network (but not included in the paper).
With a light version of TricubeNet, which excludes the MAC and Cascade Refinement, our latency is as follows.
(Dataset: HRSC2016, GPU: RTX 2080 Ti)

| Method  | Backbone  | Input Size | mAP | FPS |
| :--------: |:------------:| :-----------:| :---: | :----: |
| R<sup>2</sup> CNN | ResNet-101 | 800x800 | 73.1 | 2 |
| RRPN | ResNet-101 | 800x800 | 79.1 | 4 |
| RetinaNet-H | ResNet-101 | 800x800 | 82.9 | 14 |
| RoI Trans | ResNet-101 | 800x800 | 86.2 | 6 |
| RetinaNet-R | ResNet-101 | 800x800 | 89.2 | 10 |
| R<sup>3</sup>Det | ResNet-101 | 800x800 | 89.3 | 12 |
| | | | | |
| **TricubeNet** | ResNet-101 | 512x512 | 87.7 | 46 |
| **TricubeNet (+TTA)** | ResNet-101 | 512x512 | 88.6 | 17 |
| **TricubeNet** | DLA-34 | 512x512 | 87.1 | 70 |
| **TricubeNet (+TTA)** | DLA-34 | 512x512 | 88.4 | 30 |

As you can see, the whole inference is very fast with a light version, and there is no bottleneck in the segmentation-based post-processing algorithm.
